[project]
name = "ComfyUI-triXope"
description = "A collection of custom built ComfyUI nodes designed for film production pipelines."
version = "2.0.2"
license = {file = "LICENSE"}
dependencies = ["Pillow", "numpy", "opencv-python-headless", "av", "requests", "facexlib", "basicsr", "sageattention",]

[project.urls]
Repository = "https://github.com/triXope/Comfyuio-triXope"

[tool.comfy]
PublisherId = "trixope"
DisplayName = "Comfyui-triXope"
Icon = ""
